'use client';
import { useState } from 'react';

const pages = [
  ['HOME','A Journey Written In Curves.','Step into a visual journey where every screen opens another part of the story.','home'],
  ['INTRODUCTION','A Few Notes Before We Begin.','Follow the drawn lines, pause at a point, and read what it reveals.','intro'],
  ['UPPER CURVE','Follow The Rise.','The curve moves from low to high. Click a marker to open its story.','upper'],
  ['UPPER STORY','One Moment, Up Close.','A focused note from the upper part of the journey.','article'],
  ['UPPER STORY','The Next Page Of The Story.','Continue through the journey, then move downward when ready.','article'],
  ['LOWER CURVE','Follow The Descent.','The curve moves from high to low. Click a marker to open its story.','lower'],
  ['LOWER STORY','A Different Perspective.','A selected story from the lower curve.','article'],
  ['CLOSING NOTE','Until The Next Page.','A final reflection and a way back to the beginning.','end'],
] as const;
function Curve({lower,onStory}:{lower:boolean;onStory:(index:number)=>void}) { const path=lower?'M30 58 C70 69 85 106 112 145 S171 222 215 260 S278 300 323 310':'M30 310 C70 297 85 263 112 223 S171 146 215 104 S278 66 323 55'; const points=lower?[[67,78],[121,157],[180,230],[253,286]]:[[67,291],[121,211],[180,137],[253,80]]; return <div className="curve-wrap"><svg viewBox="0 0 350 365" className="curve"><path d={path}/>{points.map(([x,y])=><g key={x}><circle cx={x} cy={y} r="16"/><circle className="dot" cx={x} cy={y} r="6"/></g>)}</svg>{points.map(([x,y],i)=><button key={i} className="curve-point" style={{left:`calc(${x/3.5}% - 18px)`,top:`calc(${y/3.65}% - 18px)`}} onClick={()=>onStory(lower?6:i<2?3:4)} aria-label="Open curve story"/>)}</div> }
export default function Home(){const [index,setIndex]=useState(0);const [direction,setDirection]=useState<'forward'|'back'>('forward');const [kicker,title,text,kind]=pages[index];const go=(next:number)=>{setDirection(next>index?'forward':'back');setIndex((next+pages.length)%pages.length)};const isCurve=kind==='upper'||kind==='lower';return <main className="site-shell"><header><span>FIELD NOTES</span><span>VISUAL JOURNEY</span><span>{String(index+1).padStart(2,'0')} / 08</span></header><section className={`plain-page ${direction} ${kind}`} key={index}><div className="copy"><div className="number">{String(index+1).padStart(2,'0')}<i/></div><p className="kicker">{kicker}</p><h1>{title}</h1><p className="description">{text}</p>{kind==='home'&&<button className="primary" onClick={()=>go(1)}>Start journey</button>}{kind==='intro'&&<button className="outline" onClick={()=>go(2)}>Open upper curve</button>}{kind==='article'&&<div className="lines"><i/><i/><i/></div>}{kind==='end'&&<button className="outline" onClick={()=>setIndex(0)}>Start again</button>}<nav className="dots">{pages.map((_,i)=><button key={i} aria-label={`Go to page ${i+1}`} onClick={()=>{setDirection(i>index?'forward':'back');setIndex(i)}} className={i===index?'active':''}/>)}</nav></div><div className="visual">{isCurve?<Curve lower={kind==='lower'} onStory={go}/>:<div className="edge-shape"/>}<div className="nav-wedge"><i/><i/></div><div className="controls"><button onClick={()=>go(index-1)} aria-label="Previous page">↗</button><button onClick={()=>go(index)} aria-label="Stay on page">○</button><button onClick={()=>go(index+1)} aria-label="Next page">↘</button></div></div></section><p className="hint">Curve markers open stories. The controls are inside the navigation wedge.</p></main>}
